name: service-mlops
ray_serve_config:
  import_path: anyscale_service:entrypoint
  runtime_env:
    working_dir: "https://github.com/anyscale/mlops-course/archive/refs/heads/kf-dev.zip"
project_id: prj_7b48zz24ac275yc4j3emjmz55p
cluster_env: mlops_env:1
compute_config: train_config
