# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: "notebooks"
    -   id: check-yaml
        exclude: "mkdocs.yml"
- repo: local
  hooks:
    -   id: clean  # clean before test so we don't run expensive test runs again
        name: clean
        entry: make
        args: ["clean"]
        language: system
        pass_filenames: false
    -   id: test
        name: test
        entry: make
        args: ["test"]
        language: system
        pass_filenames: false
    -   id: clean  # clean after test to remove any unwanted artifacts from testing
        name: clean
        entry: make
        args: ["clean"]
        language: system
        pass_filenames: false
