cloud: anyscale-v2-cloud-fast-startup
region: us-west2
head_node_type:
  name: head_node_type
  instance_type: m5.2xlarge
worker_node_types:
- name: gpu_worker
  instance_type: g4dn.4xlarge
  min_workers: 0
  max_workers: 2
  use_spot: False
aws:
  BlockDeviceMappings:
  - DeviceName: "/dev/sda1"
    Ebs:
      VolumeSize: 500
      DeleteOnTermination: true
