base_image: anyscale/ray:nightly-py310-cu118
env_vars: {}
debian_packages:
  - curl

python:
  pip_packages: []
  conda_packages: []

post_build_cmds:
  - python3 -m pip install --upgrade pip setuptools wheel
  - python3 -m pip install -r https://raw.githubusercontent.com/anyscale/mlops-course/main/requirements.txt
