base_image: anyscale/ray:2.5.0-py310-cu118
env_vars: {}
debian_packages:
  - curl

python:
  pip_packages: []
  conda_packages: []

post_build_cmds:
  - python3 -m pip install --upgrade pip setuptools wheel
  - python3 -m pip install -r https://raw.githubusercontent.com/anyscale/Made-With-ML/main/requirements.txt
  - python3 -m pip install -U "ray[air] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp310-cp310-manylinux2014_x86_64.whl"
