cloud: madewithml-us-east-2
region: us-east2
head_node_type:
  name: head_node_type
  instance_type: m5.2xlarge
worker_node_types:
- name: gpu_worker
  instance_type: g4dn.4xlarge
  min_workers: 1
  max_workers: 1
  use_spot: False
aws:
  BlockDeviceMappings:
  - DeviceName: "/dev/sda1"
    Ebs:
      VolumeSize: 500
      DeleteOnTermination: true
