# Set up AWS credentials
- name: Set up AWS credentials
  uses: aws-actions/configure-aws-credentials@v2
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
    aws-region: us-west-2

# Checkout our repository
- name: Checkout repo
  uses: actions/checkout@v3

# Set up the appropriate Python version
- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.10.11'
    cache: 'pip'

# Install our Python dependencies
- name: Install dependencies
  run: |
    python -m pip install -e ".[deploy]" --no-cache-dir
    npm install fs

# Set all the global variables that we'll use across steps and jobs
- name: Set global vars
  run: |
    echo ANYSCALE_HOST=https://console.anyscale-staging.com >> $GITHUB_ENV
    echo ANYSCALE_CLI_TOKEN=${{ secrets.ANYSCALE_CLI_TOKEN }} >> $GITHUB_ENV
    echo CLUSTER_ENV_NAME=madewithml-cluster-env >> $GITHUB_ENV
    echo S3_BUCKET=s3://madewithml >> $GITHUB_ENV
    echo GITHUB_USERNAME=${{ github.actor }} >> $GITHUB_ENV
    echo COMMIT_ID=$(echo {{ github.event.pull_request.head.sha }} | cut -c 1-7) >> $GITHUB_ENV