name: workloads
on:
  workflow_dispatch:  # for ability to manually trigger workflow
  pull_request:
    branches:
    - main  # triggered on PRs to the main branch

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:

      # Create cluster environment (if needed)
      - name: Create cluster env (if needed)
        run: |
          echo "Creating cluster env"

  evaluate-model:
    runs-on: ubuntu-22.04
    needs: setup
    steps:

      # Test code + data
      - name: Test code + data
        run: |
          echo "Testing code + data"

      # Train our model (could also tune)
      - name: Train model
        run: |
          echo "Training model"

      # Get run ID
      - name: Get run ID
        run: |
          echo "Run ID:"

      # Evaluate our model
      - name: Evaluate model
        run: |
          python deploy/utils.py submit-job \
            --yaml-config-fp deploy/jobs/evaluate.yaml \
            --cluster-env-name ${{ env.CLUSTER_ENV_NAME }} \
            --run-id "" \
            --commit-id ${{ env.COMMIT_ID }}
      - name: Read results from S3
        run: aws s3 cp ${{ env.S3_BUCKET }}/${{ env.GITHUB_USERNAME }}/results/${{ env.COMMIT_ID }}/evaluation_results.json evaluation_results.json
      - name: Comment results on PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: fs.readFileSync('evaluation_results.json', 'utf8')
            })

      # Test model
      - name: Test model
        run: echo "Test model"
