name: madewithml
project_id: prj_hgqw2dlbcn9lt97mulm2rrf8tp
cluster_env: madewithml-cluster-env
compute_config: madewithml-cluster-compute
ray_serve_config:
  import_path: deploy.services.serve_model:entrypoint
  runtime_env:
    working_dir: "https://github.com/anyscale/Made-With-ML/archive/refs/heads/dev.zip"
