name: service-mlops
project_id: prj_fhm9eg8b7hlc32uw9c8q7gkwkz
compute_config: madewithml-compute-config
cluster_env: madewithml-cluster-env:4
ray_serve_config:
  import_path: deploy.services.service:entrypoint
  runtime_env:
    working_dir: .
    upload_path: s3://goku-mlops/workingdir/service
    env_vars:
      EXPERIMENT_NAME: llm
