name: deploy

on:
  workflow_dispatch:  # for ability to manually trigger workflow
  push:
    branches:
      - main
permissions: write-all

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:  # outputs (that we'll reuse in other jobs)
      PR_NUM: ${{ steps.vars.outputs.RUN_ID }}
    steps:
      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-session-name: s3access
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get run ID
        id: vars
        run: |
          echo "PULL REQUEST NUM"
          echo ${{ github.event.pull_request.number }}