name: deployment
on:
  workflow_dispatch:  # for ability to manually trigger workflow
  push:
    branches:
    - main
permissions: write-all

jobs:
  setup:
    runs-on: ubuntu-22.04
    outputs:  # outputs (that we'll reuse in other jobs)
      S3_BUCKET_NAME: ${{ steps.vars.outputs.S3_BUCKET_NAME }}
      PR_PATH: ${{ steps.vars.outputs.PR_PATH }}
      COMMIT_PATH: ${{ steps.vars.outputs.COMMIT_PATH }}
      CLUSTER_ENV_NAME: ${{ steps.vars.outputs.CLUSTER_ENV_NAME }}
    steps:
      - run: |
          export x1=export-works
          x2=no-export-works
          echo $x1
          echo $x2
          echo "PR_PATH=s3://$x1"
          echo "PR_PATH=s3://${x1}"
          echo "PR_PATH=s3://$x2"
          echo "PR_PATH=s3://${x2}"
      - if: github.event_name == 'push'
        run: |
          REPO=$GITHUB_REPOSITORY | awk '{print tolower($0)}'
          PR_NUM=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$REPO/commits/$GITHUB_SHA/pulls" \
            | jq -r '.[0].number')
          echo "PR_NUM=$PR_NUM" >> $GITHUB_ENV
      - run: echo "S3_BUCKET_NAME=madewithml" >> $GITHUB_ENV
      - run: echo "PR_PATH=s3://${{ env.S3_BUCKET_NAME }}/${{ github.actor }}/pull_requests/${{ env.PR_NUM }}" >> $GITHUB_ENV
      - run: echo "COMMIT_PATH=${{ env.PR_PATH }}/commits/${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
      - name: Set global vars
        id: vars
        run: |
          echo "S3_BUCKET_NAME=${{ env.S3_BUCKET_NAME }}" >> $GITHUB_OUTPUT
          echo "PR_PATH=${{ env.PR_PATH }}" >> $GITHUB_OUTPUT
          echo "COMMIT_PATH=${{ env.COMMIT_PATH }}" >> $GITHUB_OUTPUT
          echo "CLUSTER_ENV_NAME=madewithml-cluster-env" >> $GITHUB_OUTPUT

  serve-model:
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' }}
    needs: setup
    outputs:  # outputs (that we'll reuse in other jobs)
      PR_NUM: ${{ steps.vars.outputs.RUN_ID }}
    steps:

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-session-name: s3access
          aws-region: ${{ secrets.AWS_REGION }}

      # Set up dependencies
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: 'pip'
      - run: python3 -m pip install anyscale==0.5.110 typer==0.7.0

      # Get run ID
      - run: echo "RUN_ID_FILE=run_id.txt" >> $GITHUB_ENV
      - name: Get run ID
        run: |
          echo ${{ needs.setup.outputs.PR_PATH }}
          echo ${{ github.event.pull_request.number }}
          aws s3 cp ${{ needs.setup.outputs.PR_PATH }}/${{ env.RUN_ID_FILE }} ${{ env.RUN_ID_FILE }}
          echo "RUN_ID=$(cat ${{ env.RUN_ID_FILE }})" >> "$GITHUB_ENV"

      # Serve model
      - name: Serve model
        run: |
          export ANYSCALE_HOST=${{ secrets.ANYSCALE_HOST }}
          export ANYSCALE_CLI_TOKEN=${{ secrets.ANYSCALE_CLI_TOKEN }}
          python deploy/utils.py rollout-service \
            --yaml-config-fp deploy/services/serve.yaml \
            --cluster-env-name $CLUSTER_ENV_NAME \
            --run-id ${{ env.RUN_ID }}
