name: documentation
on:
  push:
    branches:
    - main
jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: 'pip'  # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install -e ".[docs]" --no-cache-dir
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
      - name: Get GitHub pages URL
        run: |
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d/ -f1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d/ -f2)
          GITHUB_PAGES_URL="https://${REPO_OWNER}.github.io/${REPO_NAME}"
      - name: Display docs URL on PR
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: "Documentation deployed to ${GITHUB_PAGES_URL}"
            })
