name: evaluation
on:
  pull_request:
    branches:
    - main
jobs:
  evaluate-model:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
      - name: Install dependencies
        run: |
          python -m pip install -e ".[deploy]" --no-cache-dir
      - name: Set global vars  # can be used across steps (except this step) and jobs
        run: |
          echo ANYSCALE_HOST=https://console.anyscale-staging.com >> $GITHUB_ENV
          echo ANYSCALE_CLI_TOKEN=${{ secrets.ANYSCALE_CLI_TOKEN }} >> $GITHUB_ENV
          echo "::add-mask::$ANYSCALE_CLI_TOKEN"
          echo S3_BUCKET=s3://goku-mlops >> $GITHUB_ENV
      - name: Create cluster env
        run: |
          export CLUSTER_ENV_NAME="madewithml-cluster-env"
          echo CLUSTER_ENV_ID=$(python deploy/utils/get_latest_cluster_env_build_id.py $CLUSTER_ENV_NAME) >> $GITHUB_ENV
      - name: Evaluate model
        run: |
          EVAL_JOB_NAME="evaluate-$(openssl rand -hex 4)"
          python deploy/utils/job_submit.py deploy/jobs/evaluate.yaml \
            project_id=prj_8tqvub3w9wherks256xlra9ch4 \
            job_name=$EVAL_JOB_NAME \
            build_id=${{ env.CLUSTER_ENV_ID }} \
            upload_path=${{ env.S3_BUCKET }}/workingdir/job \
            experiment_name=llm
