name: evaluation
on:
  pull_request:
    branches:
    - main
jobs:
  evaluate-model:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
      - name: Caching
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        run: |
          python -m pip install -e ".[deploy]" --no-cache-dir
      - name: Evaluate model
        run: anyscale job submit deploy/jobs/evaluate.yaml
