name: ml-workloads
on:
  pull_request:
    branches:
    - main  # triggered on PRs to the main branch

jobs:
  evaluate-model:
    runs-on: ubuntu-latest
    steps:

      # Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      # Checkout our repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Set up the appropriate Python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: 'pip'

      # Install our Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install -e ".[deploy]" --no-cache-dir
          npm install fs

      # Set all the global variables that we'll use across steps and jobs
      - name: Set global vars
        run: |
          echo ANYSCALE_HOST=https://console.anyscale-staging.com >> $GITHUB_ENV
          echo ANYSCALE_CLI_TOKEN=${{ secrets.ANYSCALE_CLI_TOKEN }} >> $GITHUB_ENV
          echo CLUSTER_ENV_NAME=madewithml-cluster-env >> $GITHUB_ENV
          echo S3_BUCKET=s3://madewithml >> $GITHUB_ENV
          echo GITHUB_USERNAME=${{ github.actor }} >> $GITHUB_ENV
          echo COMMIT_ID=$(echo ${{ github.sha }} | cut -c 1-7) >> $GITHUB_ENV

      # Create cluster environment (if needed)
      - name: Create cluster env (if needed)
        run: |
          echo "Creating cluster env"
          echo ${{ env.ANYSCALE_CLI_TOKEN }}
          echo ${{ env.GITHUB_USERNAME }}
          echo ${{ env.COMMIT_ID }}
          echo echo ${{ github.event.pull_request.head.sha }} | cut -c 1-7

      # Test code + data
      - name: Train code + data
        run: echo "Testing code + data"

      # Train our model (could also tune)
      - name: Train model
        run: echo "Training model"

      # Get run ID
      - name: Get run ID
        run: echo "Run ID:"

      # Evaluate our model
      - name: Evaluate model
        run: |
          python deploy/app.py submit-job \
            --yaml-config-fp deploy/jobs/evaluate.yaml \
            --cluster-env-name ${{ env.CLUSTER_ENV_NAME }} \
            --run-id "" \
            --commit-id ${{ env.COMMIT_ID }}
      - run: aws s3 cp ${{ env.S3_BUCKET }}/${{ env.GITHUB_USERNAME }}/results/${{ env.COMMIT_ID }}/evaluation_results.json evaluation_results.json
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: fs.readFileSync('evaluation_results.json', 'utf8')
            })

      # Test model
      - name: Test model
        run: echo "Test model"