name: serve
on:
  workflow_dispatch:  # manual
  push:
    branches:
    - main
permissions: write-all

jobs:
  serve:
    runs-on: ubuntu-22.04
    steps:

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::593241322649:role/github-actions-madewithml
          role-session-name: s3access
          aws-region: us-west-2

      # Set up dependencies
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: 'pip'
      - run: python3 -m pip install anyscale==0.5.131 typer==0.9.0

      # Serve model
      - name: Serve model
        run: |
          export ANYSCALE_HOST=${{ secrets.ANYSCALE_HOST }}
          export ANYSCALE_CLI_TOKEN=${{ secrets.ANYSCALE_CLI_TOKEN }}
          anyscale service rollout --service-config-file deploy/services/serve_model.yaml
