name: testing
on:
  pull_request:
    branches:
    - main
jobs:
  test-code-data-model:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
      - name: Caching
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        run: |
          python -m pip install -e ".[dev]" --no-cache-dir
      - name: Test code
        run: |
          python3 -m pytest tests/code --cov src/madewithml --cov-config=pyproject.toml --cov-report html --disable-warnings > ./test_code_results.json
      - name: Test data
        run: |
          DATASET_LOC="https://raw.githubusercontent.com/GokuMohandas/Made-With-ML/main/datasets/madewithml/dataset.csv"
          pytest --dataset-loc=$DATASET_LOC tests/data --disable-warnings > ./test_data_results.json
      - name: Test model
        run: |
          EXPERIMENT_NAME="llm"
          RUN_ID=$(python -c "from madewithml.predict import get_best_run_id as g; print(g('$EXPERIMENT_NAME', 'val_loss', 'ASC'))")
          pytest --run-id=$RUN_ID tests/model --disable-warnings > ./test_model_results.json
