name: workloads
on:
  workflow_dispatch:  # manual
  pull_request:
    branches:
    - main
permissions: write-all

jobs:
  workloads:
    runs-on: ubuntu-22.04
    steps:

      # Set up dependencies
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: 'pip'
      - run: python3 -m pip install anyscale==0.5.116 typer==0.9.0

      # Run workloads
      - name: Workloads
        run: |
          export ANYSCALE_HOST=${{ secrets.ANYSCALE_HOST }}
          export ANYSCALE_CLI_TOKEN=${{ secrets.ANYSCALE_CLI_TOKEN }}
          anyscale jobs submit deploy/jobs/workloads.yaml --wait
